# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def evenFibSum(limit):
    sum = 0
    x = 1 # Current Number in Fibonacci Sequence
    y = 2 # Next Number in Fibonacci Sequence
    while x <= limit:
        if x%2 == 0:
            sum = sum + x
        x, y = y, x + y
    return sum

print(evenFibSum(4000000))
